// Item Profile no longer sets Quantity — new items start at 0 stock, and the
// only thing that can move quantity afterward is Stock In (see
// InventoryContext.stockIn / services/inventoryService.stockIn), which also
// writes a row to the Stock Movement Log. That's why there's a "History" tab
// now alongside the item list: it's the same page, not a separate route.
//
// Edit is deliberately narrow — Name / Type / Unit only, matching
// updateItemBasics(). It doesn't touch Supplier, Reorder Level, or the
// type-specific fields, so it can't clobber data it doesn't show.
//
// Splitting this into components/inventory/* is still deferred (see the
// original note this replaced) — the file's just bigger now.

import { useEffect, useState } from "react";
import useInventory from "../hooks/useInventory";
import { useToast } from "../context/ToastContext";
import { INVENTORY_STATUS } from "../services/inventoryService";
import { card, colors, primaryButton, secondaryButton, dangerButton, successButton } from "../styles/theme";
import ConfirmDialog from "../components/common/ConfirmDialog";

const CREATE_FORM_DEFAULTS = {
  name: "",
  type: "CHEMICAL",
  unit: "L",
  cost: "",
  supplier: "",
  reorderLevel: "",
  chemicalType: "INSECTICIDE",
  expirationDate: "",
  safetyLevel: "",
  hazardRating: "",
  dateReceived: "",
  serialNumber: "",
  condition: "ACTIVE",
  lastMaintenanceDate: "",
  nextMaintenanceDate: "",
  manufacturer: "",
  model: "",
  materialCategory: "SUPPLIES",
  description: "",
};

function InventoryPage() {
  const {
    inventory,
    addItem: onAddItem,
    updateItemBasics,
    setItemStatus,
    stockIn,
    loading,
    error,
    movements,
    movementsLoading,
    movementsError,
    refreshMovements,
  } = useInventory();
  const { showSuccess, showError } = useToast();

  const [tab, setTab] = useState("items"); // "items" | "history"
  const [openForm, setOpenForm] = useState(false);
  const [selectedItem, setSelectedItem] = useState(null);
  const [editItem, setEditItem] = useState(null);
  const [stockInItem, setStockInItem] = useState(null);
  const [disableTarget, setDisableTarget] = useState(null);
  const [form, setForm] = useState(CREATE_FORM_DEFAULTS);

  useEffect(() => {
    if (tab === "history") refreshMovements();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab]);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setForm((previous) => ({ ...previous, [name]: value }));
  };

  const handleTypeChange = (event) => {
    const newType = event.target.value;
    setForm((previous) => ({
      ...previous,
      type: newType,
      chemicalType: "INSECTICIDE",
      expirationDate: "",
      safetyLevel: "",
      hazardRating: "",
      dateReceived: "",
      serialNumber: "",
      condition: "ACTIVE",
      lastMaintenanceDate: "",
      nextMaintenanceDate: "",
      manufacturer: "",
      model: "",
      materialCategory: "SUPPLIES",
      description: "",
    }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();

    // No quantity here — items are created at 0 stock. id / createdAt /
    // updatedAt / status are generated by the database.
    const newItem = {
      name: form.name.trim(),
      type: form.type,
      unit: form.unit,
      cost: Number(form.cost),
      supplier: form.supplier || null,
      reorderLevel: form.reorderLevel ? Number(form.reorderLevel) : null,
    };

    if (form.type === "CHEMICAL") {
      newItem.chemicalType = form.chemicalType;
      newItem.expirationDate = form.expirationDate || null;
      newItem.safetyLevel = form.safetyLevel || null;
      newItem.hazardRating = form.hazardRating || null;
      newItem.dateReceived = form.dateReceived || null;
    } else if (form.type === "EQUIPMENT") {
      newItem.serialNumber = form.serialNumber || null;
      newItem.condition = form.condition;
      newItem.lastMaintenanceDate = form.lastMaintenanceDate || null;
      newItem.nextMaintenanceDate = form.nextMaintenanceDate || null;
      newItem.manufacturer = form.manufacturer || null;
      newItem.model = form.model || null;
    } else if (form.type === "MATERIAL") {
      newItem.materialCategory = form.materialCategory;
      newItem.description = form.description || null;
    }

    if (!newItem.name || Number.isNaN(newItem.cost)) return;

    const result = await onAddItem(newItem);
    if (result !== true) {
      showError(typeof result === "string" ? result : "Could not save the item.");
      return;
    }

    showSuccess(`${newItem.name} added to inventory. It starts at 0 stock — use Stock In to add quantity.`);
    setForm(CREATE_FORM_DEFAULTS);
    setOpenForm(false);
  };

  return (
    <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
      <div style={{ marginBottom: "1.25rem", display: "flex", justifyContent: "space-between", alignItems: "center", gap: "1rem", flexWrap: "wrap" }}>
        <div>
          <p style={{ color: colors.brandInk, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", fontSize: "0.75rem" }}>
            Inventory
          </p>
          <h1 style={{ margin: "0.2rem 0 0", fontSize: "2rem", color: "#111827" }}>Item Profile</h1>
        </div>
        {tab === "items" && (
          <button type="button" onClick={() => setOpenForm((value) => !value)} style={primaryButton}>
            {openForm ? "Close Form" : "Add Inventory Item"}
          </button>
        )}
      </div>

      <div style={{ display: "flex", gap: "0.5rem", marginBottom: "1.25rem", borderBottom: `2px solid #f0f0f0` }}>
        <TabButton active={tab === "items"} onClick={() => setTab("items")}>
          Items
        </TabButton>
        <TabButton active={tab === "history"} onClick={() => setTab("history")}>
          Stock Movement History
        </TabButton>
      </div>

      {tab === "items" && (
        <>
          {openForm && (
            <form onSubmit={handleSubmit} style={{ ...card, marginBottom: "1.5rem" }}>
              <div style={{ marginBottom: "1.5rem", borderBottom: "2px solid #f0f0f0", paddingBottom: "1rem" }}>
                <h3 style={{ color: "#111827", marginBottom: "1rem" }}>Basic Information</h3>
                <p style={{ margin: "0 0 1rem", color: "#6b7280", fontSize: "0.85rem" }}>
                  New items start at 0 stock. Add quantity afterward with Stock In on the item's row.
                </p>
                <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1rem" }}>
                  <Field label="Item Name *">
                    <input name="name" value={form.name} onChange={handleChange} style={inputStyle} placeholder="Enter item name" required />
                  </Field>
                  <Field label="Type *">
                    <select name="type" value={form.type} onChange={handleTypeChange} style={inputStyle} required>
                      <option value="CHEMICAL">Chemical</option>
                      <option value="EQUIPMENT">Equipment</option>
                      <option value="MATERIAL">Material</option>
                    </select>
                  </Field>
                  <Field label="Unit *">
                    <input name="unit" value={form.unit} onChange={handleChange} style={inputStyle} placeholder="L, kg, pcs, etc." required />
                  </Field>
                  <Field label="Cost per Unit (₱) *">
                    <input name="cost" type="number" min="0" step="0.01" value={form.cost} onChange={handleChange} style={inputStyle} placeholder="0.00" required />
                  </Field>
                  <Field label="Supplier">
                    <input name="supplier" value={form.supplier} onChange={handleChange} style={inputStyle} placeholder="Supplier name" />
                  </Field>
                  <Field label="Reorder Level">
                    <input name="reorderLevel" type="number" min="0" step="0.1" value={form.reorderLevel} onChange={handleChange} style={inputStyle} placeholder="0" />
                  </Field>
                </div>
              </div>

              {form.type === "CHEMICAL" && (
                <div style={{ marginBottom: "1.5rem", borderBottom: "2px solid #f0f0f0", paddingBottom: "1rem" }}>
                  <h3 style={{ color: "#111827", marginBottom: "1rem" }}>Chemical Details</h3>
                  <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1rem" }}>
                    <Field label="Chemical Type *">
                      <select name="chemicalType" value={form.chemicalType} onChange={handleChange} style={inputStyle} required>
                        <option value="INSECTICIDE">Insecticide</option>
                        <option value="FUNGICIDE">Fungicide</option>
                        <option value="RODENTICIDE">Rodenticide</option>
                        <option value="HERBICIDE">Herbicide</option>
                        <option value="FUMIGANT">Fumigant</option>
                        <option value="OTHER">Other</option>
                      </select>
                    </Field>
                    <Field label="Expiration Date">
                      <input name="expirationDate" type="date" value={form.expirationDate} onChange={handleChange} style={inputStyle} />
                    </Field>
                    <Field label="Safety Level">
                      <input name="safetyLevel" value={form.safetyLevel} onChange={handleChange} style={inputStyle} placeholder="Low, Medium, High" />
                    </Field>
                    <Field label="Hazard Rating">
                      <input name="hazardRating" value={form.hazardRating} onChange={handleChange} style={inputStyle} placeholder="Hazard description" />
                    </Field>
                    <Field label="Date Received">
                      <input name="dateReceived" type="date" value={form.dateReceived} onChange={handleChange} style={inputStyle} />
                    </Field>
                  </div>
                </div>
              )}

              {form.type === "EQUIPMENT" && (
                <div style={{ marginBottom: "1.5rem", borderBottom: "2px solid #f0f0f0", paddingBottom: "1rem" }}>
                  <h3 style={{ color: "#111827", marginBottom: "1rem" }}>Equipment Details</h3>
                  <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1rem" }}>
                    <Field label="Serial Number">
                      <input name="serialNumber" value={form.serialNumber} onChange={handleChange} style={inputStyle} placeholder="Serial number" />
                    </Field>
                    <Field label="Condition *">
                      <select name="condition" value={form.condition} onChange={handleChange} style={inputStyle} required>
                        <option value="ACTIVE">Active</option>
                        <option value="MAINTENANCE">Maintenance</option>
                        <option value="DAMAGED">Damaged</option>
                        <option value="INACTIVE">Inactive</option>
                      </select>
                    </Field>
                    <Field label="Manufacturer">
                      <input name="manufacturer" value={form.manufacturer} onChange={handleChange} style={inputStyle} placeholder="Manufacturer name" />
                    </Field>
                    <Field label="Model">
                      <input name="model" value={form.model} onChange={handleChange} style={inputStyle} placeholder="Model name/number" />
                    </Field>
                    <Field label="Last Maintenance Date">
                      <input name="lastMaintenanceDate" type="date" value={form.lastMaintenanceDate} onChange={handleChange} style={inputStyle} />
                    </Field>
                    <Field label="Next Maintenance Date">
                      <input name="nextMaintenanceDate" type="date" value={form.nextMaintenanceDate} onChange={handleChange} style={inputStyle} />
                    </Field>
                  </div>
                </div>
              )}

              {form.type === "MATERIAL" && (
                <div style={{ marginBottom: "1.5rem", borderBottom: "2px solid #f0f0f0", paddingBottom: "1rem" }}>
                  <h3 style={{ color: "#111827", marginBottom: "1rem" }}>Material Details</h3>
                  <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1rem" }}>
                    <Field label="Material Category *">
                      <select name="materialCategory" value={form.materialCategory} onChange={handleChange} style={inputStyle} required>
                        <option value="PROTECTIVE_GEAR">Protective Gear</option>
                        <option value="SUPPLIES">Supplies</option>
                        <option value="TOOLS_ACCESSORIES">Tools & Accessories</option>
                        <option value="OTHER">Other</option>
                      </select>
                    </Field>
                    <Field label="Description" style={{ gridColumn: "1 / -1" }}>
                      <textarea name="description" value={form.description} onChange={handleChange} style={{ ...inputStyle, minHeight: "100px", resize: "vertical" }} placeholder="Description of material" />
                    </Field>
                  </div>
                </div>
              )}

              <div style={{ display: "flex", justifyContent: "flex-end", marginTop: "1rem", gap: "0.5rem" }}>
                <button type="button" onClick={() => setOpenForm(false)} style={secondaryButton}>
                  Cancel
                </button>
                <button type="submit" style={{ background: "#8b1e1e", color: "#fff", border: "none", borderRadius: "10px", padding: "0.8rem 1rem", fontWeight: 700, cursor: "pointer" }}>
                  Add Item
                </button>
              </div>
            </form>
          )}

          <div style={{ ...card, padding: 0, overflow: "hidden" }}>
            <div style={{ display: "grid", gridTemplateColumns: "2fr 1.1fr 0.7fr 0.9fr 1fr 1.6fr", gap: "0.75rem", padding: "1rem 1.25rem", background: "#fafafa", fontWeight: 700, color: "#374151" }}>
              <span>Item Name</span>
              <span>Type</span>
              <span>Unit</span>
              <span>Quantity</span>
              <span>Info</span>
              <span>Actions</span>
            </div>

            {error && (
              <div style={{ padding: "1.25rem", color: "#b91c1c", background: "#fef2f2" }}>
                Could not load inventory — {error}
              </div>
            )}

            {!error && loading && (
              <div style={{ padding: "1.25rem", color: "#6b7280" }}>Loading inventory…</div>
            )}

            {!error && !loading && inventory.length === 0 && (
              <div style={{ padding: "1.25rem", color: "#6b7280" }}>
                No inventory items yet. Add one using the form above.
              </div>
            )}

            {inventory.map((item) => {
              const isLowStock = item.reorderLevel && item.quantity <= item.reorderLevel;
              const isDisabled = item.status === INVENTORY_STATUS.DISABLED;
              const typeLabel = item.type === "CHEMICAL" ? "Chemical" : item.type === "EQUIPMENT" ? "Equipment" : "Material";

              return (
                <div
                  key={item.id}
                  onClick={() => setSelectedItem(item)}
                  style={{
                    display: "grid",
                    gridTemplateColumns: "2fr 1.1fr 0.7fr 0.9fr 1fr 1.6fr",
                    gap: "0.75rem",
                    padding: "1rem 1.25rem",
                    borderTop: "1px solid #f1f1f1",
                    alignItems: "center",
                    cursor: "pointer",
                    transition: "background-color 0.2s",
                    opacity: isDisabled ? 0.55 : 1,
                    background: isDisabled ? "#fafafa" : "transparent",
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = isDisabled ? "#f3f4f6" : "#f9f9f9")}
                  onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = isDisabled ? "#fafafa" : "transparent")}
                >
                  <div>
                    <div style={{ fontWeight: 700, color: "#111827" }}>
                      {item.name}
                      {isDisabled && (
                        <span style={{ marginLeft: "0.5rem", fontSize: "0.7rem", fontWeight: 700, color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                          Disabled
                        </span>
                      )}
                    </div>
                    {item.supplier && <div style={{ fontSize: "0.85rem", color: "#6b7280" }}>{item.supplier}</div>}
                  </div>
                  <div style={{ color: "#374151" }}>{typeLabel}</div>
                  <div style={{ color: "#374151" }}>{item.unit}</div>
                  <div style={{ fontWeight: 700, color: isLowStock ? "#b91c1c" : "#111827" }}>{item.quantity}</div>
                  <div>
                    {isDisabled ? (
                      <span style={{ background: "#f3f4f6", color: "#4b5563", borderRadius: "999px", padding: "0.35rem 0.7rem", fontSize: "0.75rem", fontWeight: 700 }}>
                        Disabled
                      </span>
                    ) : isLowStock ? (
                      <span style={{ background: "#fee2e2", color: "#991b1b", borderRadius: "999px", padding: "0.35rem 0.7rem", fontSize: "0.75rem", fontWeight: 700 }}>
                        Low Stock
                      </span>
                    ) : (
                      <span style={{ background: "#dcfce7", color: "#166534", borderRadius: "999px", padding: "0.35rem 0.7rem", fontSize: "0.75rem", fontWeight: 700 }}>
                        Healthy
                      </span>
                    )}
                  </div>
                  <div style={{ display: "flex", gap: "0.4rem", flexWrap: "wrap" }} onClick={(e) => e.stopPropagation()}>
                    <button type="button" onClick={() => setEditItem(item)} style={actionButtonStyle}>
                      Edit
                    </button>
                    <button
                      type="button"
                      disabled={isDisabled}
                      onClick={() => !isDisabled && setStockInItem(item)}
                      style={buttonWhen(isDisabled, successButton, actionButtonSize)}
                      title={isDisabled ? "Enable this item to add stock" : "Record a Stock In"}
                    >
                      Stock In
                    </button>
                    {isDisabled ? (
                      <button type="button" onClick={() => setItemStatus(item.id, INVENTORY_STATUS.ACTIVE).then((r) => handleStatusResult(r, showSuccess, showError, item.name, "enabled"))} style={{ ...actionButtonStyle }}>
                        Enable
                      </button>
                    ) : (
                      <button type="button" onClick={() => setDisableTarget(item)} style={{ ...dangerButton, ...actionButtonSize }}>
                        Disable
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </>
      )}

      {tab === "history" && (
        <div style={{ ...card, padding: 0, overflow: "hidden" }}>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1.6fr 0.9fr 1.2fr 1fr", gap: "0.75rem", padding: "1rem 1.25rem", background: "#fafafa", fontWeight: 700, color: "#374151" }}>
            <span>Date</span>
            <span>Item</span>
            <span>Amount</span>
            <span>Reference</span>
            <span>Recorded By</span>
          </div>

          {movementsError && (
            <div style={{ padding: "1.25rem", color: "#b91c1c", background: "#fef2f2" }}>
              Could not load history — {movementsError}
            </div>
          )}

          {!movementsError && movementsLoading && (
            <div style={{ padding: "1.25rem", color: "#6b7280" }}>Loading history…</div>
          )}

          {!movementsError && !movementsLoading && movements.length === 0 && (
            <div style={{ padding: "1.25rem", color: "#6b7280" }}>
              No Stock In records yet. They'll show up here once you add stock to an item.
            </div>
          )}

          {movements.map((movement) => (
            <div
              key={movement.id}
              style={{
                display: "grid",
                gridTemplateColumns: "1fr 1.6fr 0.9fr 1.2fr 1fr",
                gap: "0.75rem",
                padding: "1rem 1.25rem",
                borderTop: "1px solid #f1f1f1",
                alignItems: "center",
              }}
            >
              <div style={{ color: "#374151" }}>{new Date(movement.movementDate).toLocaleDateString()}</div>
              <div style={{ fontWeight: 700, color: "#111827" }}>{movement.itemName}</div>
              <div style={{ fontWeight: 700, color: "#166534" }}>
                +{movement.amount} {movement.itemUnit}
              </div>
              <div style={{ color: "#6b7280" }}>{movement.reference || "—"}</div>
              <div style={{ color: "#6b7280" }}>{movement.actor || "—"}</div>
            </div>
          ))}
        </div>
      )}

      {selectedItem && <InventoryDetailModal item={selectedItem} onClose={() => setSelectedItem(null)} />}

      {editItem && (
        <EditItemModal
          item={editItem}
          onClose={() => setEditItem(null)}
          onSave={async (values) => {
            const result = await updateItemBasics(editItem.id, values);
            if (result !== true) {
              showError(typeof result === "string" ? result : "Could not update the item.");
              return false;
            }
            showSuccess(`${values.name} updated.`);
            setEditItem(null);
            return true;
          }}
        />
      )}

      {stockInItem && (
        <StockInModal
          item={stockInItem}
          onClose={() => setStockInItem(null)}
          onSubmit={async (values) => {
            const result = await stockIn(stockInItem.id, values);
            if (result !== true) {
              showError(typeof result === "string" ? result : "Could not record the Stock In.");
              return false;
            }
            showSuccess(`Added ${values.amount} ${stockInItem.unit} to ${stockInItem.name}.`);
            setStockInItem(null);
            return true;
          }}
        />
      )}

      <ConfirmDialog
        open={!!disableTarget}
        title="Disable this item?"
        message={
          disableTarget
            ? `"${disableTarget.name}" will be greyed out and Stock In will be blocked until you re-enable it. Its current quantity and history stay intact — nothing is deleted.`
            : ""
        }
        confirmLabel="Disable"
        tone="danger"
        onConfirm={async () => {
          const target = disableTarget;
          setDisableTarget(null);
          const result = await setItemStatus(target.id, INVENTORY_STATUS.DISABLED);
          if (result !== true) {
            showError(typeof result === "string" ? result : "Could not disable the item.");
            return;
          }
          showSuccess(`${target.name} disabled.`);
        }}
        onCancel={() => setDisableTarget(null)}
      />
    </div>
  );
}

async function handleStatusResult(result, showSuccess, showError, name, verb) {
  if (result !== true) {
    showError(typeof result === "string" ? result : `Could not update ${name}.`);
    return;
  }
  showSuccess(`${name} ${verb}.`);
}

function TabButton({ active, onClick, children }) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        border: "none",
        background: "none",
        padding: "0.75rem 0.25rem",
        marginBottom: "-2px",
        borderBottom: active ? `3px solid ${colors.brandLight}` : "3px solid transparent",
        color: active ? colors.brandInk : "#6b7280",
        fontWeight: 700,
        cursor: "pointer",
        fontSize: "0.95rem",
      }}
    >
      {children}
    </button>
  );
}

function EditItemModal({ item, onClose, onSave }) {
  const [values, setValues] = useState({ name: item.name, type: item.type, unit: item.unit });
  const [saving, setSaving] = useState(false);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setValues((previous) => ({ ...previous, [name]: value }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!values.name.trim() || !values.unit.trim()) return;
    setSaving(true);
    await onSave({ name: values.name.trim(), type: values.type, unit: values.unit.trim() });
    setSaving(false);
  };

  return (
    <ModalShell onClose={onClose} title={`Edit "${item.name}"`}>
      <form onSubmit={handleSubmit}>
        <p style={{ margin: "0 0 1.25rem", color: "#6b7280", fontSize: "0.85rem" }}>
          Edit covers Name, Type, and Unit only. Supplier, Reorder Level, and type-specific details aren't editable here yet.
        </p>
        <div style={{ display: "grid", gap: "1rem" }}>
          <Field label="Item Name *">
            <input name="name" value={values.name} onChange={handleChange} style={inputStyle} required />
          </Field>
          <Field label="Type *">
            <select name="type" value={values.type} onChange={handleChange} style={inputStyle} required>
              <option value="CHEMICAL">Chemical</option>
              <option value="EQUIPMENT">Equipment</option>
              <option value="MATERIAL">Material</option>
            </select>
          </Field>
          <Field label="Unit *">
            <input name="unit" value={values.unit} onChange={handleChange} style={inputStyle} required />
          </Field>
        </div>

        <div style={{ display: "flex", justifyContent: "flex-end", marginTop: "1.5rem", gap: "0.5rem" }}>
          <button type="button" onClick={onClose} style={secondaryButton}>
            Cancel
          </button>
          <button type="submit" disabled={saving} style={buttonWhen(saving)}>
            {saving ? "Saving…" : "Save Changes"}
          </button>
        </div>
      </form>
    </ModalShell>
  );
}

function StockInModal({ item, onClose, onSubmit }) {
  const [amount, setAmount] = useState("");
  const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [reference, setReference] = useState("");
  const [saving, setSaving] = useState(false);

  const handleSubmit = async (event) => {
    event.preventDefault();
    const numericAmount = Number(amount);
    if (!numericAmount || numericAmount <= 0 || !date) return;
    setSaving(true);
    await onSubmit({ amount: numericAmount, date, reference: reference.trim() });
    setSaving(false);
  };

  return (
    <ModalShell onClose={onClose} title={`Stock In — ${item.name}`}>
      <form onSubmit={handleSubmit}>
        <p style={{ margin: "0 0 1.25rem", color: "#6b7280", fontSize: "0.85rem" }}>
          Current stock: <strong>{item.quantity} {item.unit}</strong>. This adds to it and writes a Stock Movement Log entry.
        </p>
        <div style={{ display: "grid", gap: "1rem" }}>
          <Field label={`Amount (${item.unit}) *`}>
            <input type="number" min="0" step="0.1" value={amount} onChange={(e) => setAmount(e.target.value)} style={inputStyle} placeholder="0" required autoFocus />
          </Field>
          <Field label="Date *">
            <input type="date" value={date} onChange={(e) => setDate(e.target.value)} style={inputStyle} required />
          </Field>
          <Field label="Reference (optional)">
            <input value={reference} onChange={(e) => setReference(e.target.value)} style={inputStyle} placeholder="PO number, delivery note, etc." />
          </Field>
        </div>

        <div style={{ display: "flex", justifyContent: "flex-end", marginTop: "1.5rem", gap: "0.5rem" }}>
          <button type="button" onClick={onClose} style={secondaryButton}>
            Cancel
          </button>
          <button type="submit" disabled={saving} style={buttonWhen(saving, successButton)}>
            {saving ? "Saving…" : "Add Stock"}
          </button>
        </div>
      </form>
    </ModalShell>
  );
}

function ModalShell({ title, onClose, children }) {
  return (
    <div
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "rgba(0, 0, 0, 0.5)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: "linear-gradient(180deg, #ffffff 0%, #fff8f8 100%)",
          border: `2px solid ${colors.brandLight}`,
          borderRadius: "16px",
          padding: "2rem",
          maxWidth: "480px",
          width: "90%",
          maxHeight: "80vh",
          overflowY: "auto",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.25rem", borderBottom: "2px solid #f0f0f0", paddingBottom: "1rem" }}>
          <h2 style={{ margin: 0, color: colors.brandInk, fontSize: "1.25rem" }}>{title}</h2>
          <button onClick={onClose} type="button" style={{ background: "none", border: "none", fontSize: "1.5rem", cursor: "pointer", color: "#6b7280" }}>
            ✕
          </button>
        </div>
        {children}
      </div>
    </div>
  );
}

function InventoryDetailModal({ item, onClose }) {
  const typeLabel = item.type === "CHEMICAL" ? "Chemical" : item.type === "EQUIPMENT" ? "Equipment" : "Material";

  return (
    <ModalShell onClose={onClose} title={item.name}>
      {/* Basic Information */}
      <div style={{ marginBottom: "1.5rem" }}>
        <h3 style={{ color: "#374151", fontSize: "0.875rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "0.75rem" }}>
          Basic Information
        </h3>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
          <DetailRow label="Type" value={typeLabel} />
          <DetailRow label="Status" value={item.status === "DISABLED" ? "Disabled" : "Active"} />
          <DetailRow label="Quantity" value={`${item.quantity} ${item.unit}`} />
          {item.cost !== undefined && item.cost !== null ? <DetailRow label="Cost per Unit" value={`₱${Number(item.cost).toFixed(2)}`} /> : null}
          {item.cost !== undefined && item.cost !== null && item.quantity ? <DetailRow label="Total Value" value={`₱${(item.quantity * Number(item.cost)).toFixed(2)}`} /> : null}
          {item.supplier && <DetailRow label="Supplier" value={item.supplier} />}
          {item.reorderLevel && <DetailRow label="Reorder Level" value={item.reorderLevel} />}
        </div>
      </div>

      {/* Chemical-Specific Details */}
      {item.type === "CHEMICAL" && (
        <div style={{ marginBottom: "1.5rem" }}>
          <h3 style={{ color: "#374151", fontSize: "0.875rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "0.75rem" }}>
            Chemical Details
          </h3>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
            <DetailRow label="Chemical Type" value={item.chemicalType} />
            {item.expirationDate && <DetailRow label="Expiration Date" value={new Date(item.expirationDate).toLocaleDateString()} />}
            {item.safetyLevel && <DetailRow label="Safety Level" value={item.safetyLevel} />}
            {item.hazardRating && <DetailRow label="Hazard Rating" value={item.hazardRating} />}
            {item.dateReceived && <DetailRow label="Date Received" value={new Date(item.dateReceived).toLocaleDateString()} />}
          </div>
        </div>
      )}

      {/* Equipment-Specific Details */}
      {item.type === "EQUIPMENT" && (
        <div style={{ marginBottom: "1.5rem" }}>
          <h3 style={{ color: "#374151", fontSize: "0.875rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "0.75rem" }}>
            Equipment Details
          </h3>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
            {item.serialNumber && <DetailRow label="Serial Number" value={item.serialNumber} />}
            <DetailRow label="Condition" value={item.condition} />
            {item.manufacturer && <DetailRow label="Manufacturer" value={item.manufacturer} />}
            {item.model && <DetailRow label="Model" value={item.model} />}
            {item.lastMaintenanceDate && <DetailRow label="Last Maintenance" value={new Date(item.lastMaintenanceDate).toLocaleDateString()} />}
            {item.nextMaintenanceDate && <DetailRow label="Next Maintenance" value={new Date(item.nextMaintenanceDate).toLocaleDateString()} />}
          </div>
        </div>
      )}

      {/* Material-Specific Details */}
      {item.type === "MATERIAL" && (
        <div style={{ marginBottom: "1.5rem" }}>
          <h3 style={{ color: "#374151", fontSize: "0.875rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "0.75rem" }}>
            Material Details
          </h3>
          <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: "1rem" }}>
            <DetailRow label="Material Category" value={item.materialCategory} />
            {item.description && <DetailRow label="Description" value={item.description} />}
          </div>
        </div>
      )}

      {/* Metadata */}
      <div style={{ marginTop: "1.5rem", paddingTop: "1rem", borderTop: "1px solid #f0f0f0" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem", fontSize: "0.85rem", color: "#6b7280" }}>
          <div>
            <div style={{ fontWeight: 700, color: "#374151" }}>Created</div>
            {new Date(item.createdAt).toLocaleDateString()}
          </div>
          <div>
            <div style={{ fontWeight: 700, color: "#374151" }}>Last Updated</div>
            {new Date(item.updatedAt).toLocaleDateString()}
          </div>
        </div>
      </div>

      <div style={{ display: "flex", justifyContent: "flex-end", marginTop: "1.5rem", gap: "0.5rem" }}>
        <button onClick={onClose} style={{ background: "#8b1e1e", color: "#fff", border: "none", borderRadius: "10px", padding: "0.8rem 1rem", fontWeight: 700, cursor: "pointer" }}>
          Close
        </button>
      </div>
    </ModalShell>
  );
}

function DetailRow({ label, value }) {
  return (
    <div>
      <div style={{ fontSize: "0.75rem", fontWeight: 700, color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "0.25rem" }}>
        {label}
      </div>
      <div style={{ fontSize: "0.95rem", color: "#111827", fontWeight: 600 }}>
        {value || "—"}
      </div>
    </div>
  );
}

function Field({ label, children }) {
  return (
    <label style={{ display: "grid", gap: "0.45rem", color: "#374151", fontWeight: 700 }}>
      <span>{label}</span>
      {children}
    </label>
  );
}

function buttonWhen(disabled, base = primaryButton, extra = {}) {
  return { ...base, ...extra, cursor: disabled ? "default" : "pointer", opacity: disabled ? 0.5 : 1 };
}

const actionButtonSize = {
  padding: "0.45rem 0.7rem",
  fontSize: "0.8rem",
  borderRadius: "8px",
};

const actionButtonStyle = {
  ...secondaryButton,
  ...actionButtonSize,
};

const inputStyle = {
  width: "100%",
  border: "1px solid #d9d9d9",
  borderRadius: "10px",
  padding: "0.72rem 0.8rem",
  fontSize: "0.96rem",
  background: "#ffffff",
  color: "#111827",
};

export default InventoryPage;
